{self, ...}: {
  username = "ethan";
  fullname = "12-G";
  email = "1240121425@qq.com";
  isWSL = false;
  ssh_authorized_keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEpFEBNK/5k7GbZTDz2Wcd97Vns4ShHcCKFWFCs4hKnB Generated By Termius"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICJCEWbyA2Pnm7kHh0fw4U3dHuDHAJgk8AAtetMs4BqF Generated By Termius"
  ];
  nvchadPath = "${self}/nvchad";
  pc = {
    t = "thinkbook";
    w = "wsl";
  };
  platform = {
    x86 = "x86_64-linux";
  };
}
